### ISSUE TITLE
Markdown links

### ISSUE THREAD

**Issue by redscotina** [bitrise-io/nuclino-to-confluence#1]
~/nuclino-to-confluence# python3 import.py GR ./gr-nuclino plan
2021-02-02 15:18:40,072 - INFO - check_plan_requirements [139] - Workspace Index file found ./gr-nuclino/index.md
2021-02-02 15:18:40,072 - INFO - check_plan_requirements [145] - Creating plan folder...
2021-02-02 15:18:40,072 - INFO - process_index [184] - Processing Index file index.md ...
2021-02-02 15:18:40,073 - ERROR - process_index [197] - Error: Cannot find markdown file ./gr-nuclino/<Game mechanics 53b7ad1f.md>

need recursive clear <> symbols from file links

**Comment by redscotina** [comment]
ok, i sed all files and remove <> afted and before files paths
now
#python3 import.py GR ~/GR execute

`Traceback (most recent call last):
  File "import.py", line 565, in <module>
    main()
  File "import.py", line 560, in main
    execute_import()
  File "import.py", line 531, in execute_import
    base_id = get_space_base_id()
  File "import.py", line 120, in get_space_base_id
    return data[u'_expandable'][u'homepage'][len("/rest/api/content/"):]
KeyError: 'homepage'`

wtf?

**Comment by mjones-droid** [comment]
Hey @redscotina!

This project is no longer being actively maintained by Bitrise. It was used for a one-time migration. If you want to do bug fixes or updated, we highly recommend forking this repo to continue development. 

Matthew
Senior Customer Engineer
